### ISSUE TITLE
DM5 有部份下不了

### ISSUE THREAD

**Issue by DummySYSTEM** [abc9070410/JComicDownloader#113]
例如絕望先生第10卷, 我看過URL 好像沒太大分別, 但URL 解出來都是 null

http://www.dm5.com/manhua-juewangxiansheng/

**Comment by hkgsherlock** [comment]
版本？

**Comment by DummySYSTEM** [comment]
v5.30.170505

**Comment by dxzy** [comment]
之前fix的版本好像沒放出下載

**Comment by Kennyl** [comment]
因為主repository沒有travis auto deploy.

**Comment by DummySYSTEM** [comment]
請問是那一個 fix? 我想自行解決

**Comment by hkgsherlock** [comment]
#101 ..?

**Comment by hkgsherlock** [comment]
自行 fork 到自己的 repo 然後改好再開 PR 叫我們拉回來就行

**Comment by Kennyl** [comment]
https://github.com/Kennyl/JComicDownloader/releases
暫用？

**Comment by DummySYSTEM** [comment]
我本來打算晚一點才開始修改, 多謝 Kennyl 幫忙

**Comment by DummySYSTEM** [comment]
剛剛試了一下 Kennyl 的 170914(170917), 一樣以絕望先生 Vol.10 為例但情況一樣, 直接在DM5看是沒問題的

Content-Length = 729
Download progress 1 bytes received, 0.14%Download progress 2 bytes received, 0.27%Download progress 3 bytes received, 0.41%Download progress 4 bytes received, 0.55%Download progress 10 bytes received, 1.37%Download progress 522 bytes received, 71.60%Download progress 729 bytes received, 100.00%
http://www.dm5.com/m44126/chapterfun.ashx?cid=44126&page=1&key25ac6da2b0ae9c8d&language=1&gtk=6 downloads successful! 1
全文: eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('l b(){2 5=9;2 c=\'a\';2 6="k://h-o-n-m-f.e.g/j/4/p";2 3=["/4[1-7]u.8","/4[1-7]q.8"];t(2 i=0;i<3.s;i++){3[i]=6+3[i]+\'?5=9&c=a\'}r 3}2 d;d=b();',31,31,'||var|pvalue|?望先生|cid|pix|10|jpg|44126|cd95cadee7f65014fb2d26c648d81b66|dm5imagefun|key||cdndm5|20|com|manhua1011|||http|function|111|244|61|?望先生_vol10|_第10卷_0002|return|length|for|_第10卷_0001'.split('|'),0,{}))

網址Tokens: 0 [] 1 [var] 2 [pvalue] 3 [?望先生] 4 [cid] 5 [pix] 6 [10] 7 [jpg] 8 [44126] 9 [cd95cadee7f65014fb2d26c648d81b66] 10 [dm5imagefun] 11 [key] 12 [] 13 [cdndm5] 14 [20] 15 [com] 16 [manhua1011] 17 [] 18 [] 19 [http] 20 [function] 21 [111] 22 [244] 23 [61] 24 [?望先生_vol10] 25 [_第10卷_0002] 26 [return] 27 [length] 28 [for] 29 [_第10卷_0001] 
網址Token順序:  [k]  [:]  [/]  [/]  [h]  [-]  [o]  [-]  [n]  [-]  [m]  [-]  [f]  [.]  [e]  [.]  [g]  [/]  [j]  [/]  [4]  [/]  [p] 
基本位址http://manhua1011-61-244-111-20.cdndm5.com/j/?望先生/?望先生_vol10

圖片檔名token順序:  [/4[1-7] 
 [4]  [[]  [1]  [-]  [7] 0 圖片檔名:?望先生[1-10 圖片網址:http://manhua1011-61-244-111-20.cdndm5.com/j/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F_vol10/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F[1-10?cid=44126&key=d48907c8e5f2d611167cf2d81f29ae9e
下載張數:1
REFER : http://www.dm5.com/m44126/
1 ERROR: 錯誤回傳碼(responseCode): 404 : http://manhua1011-61-244-111-20.cdndm5.com/j/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F_vol10/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F[1-10?cid=44126&key=d48907c8e5f2d611167cf2d81f29ae9e
java.lang.Exception: 錯誤回傳碼(responseCode): 404 : http://manhua1011-61-244-111-20.cdndm5.com/j/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F_vol10/%E7%BB%9D%E6%9C%9B%E5%85%88%E7%94%9F[1-10?cid=44126&key=d48907c8e5f2d611167cf2d81f29ae9e
	at jcomicdownloader.tools.Common.errorReport(Common.java:171)
	at jcomicdownloader.tools.Common.simpleDownloadFile(Common.java:2834)
	at jcomicdownloader.module.ParseOnlineComicSite.singlePageDownload(ParseOnlineComicSite.java:313)
	at jcomicdownloader.module.ParseOnlineComicSite.singlePageDownloadUsingSimple(ParseOnlineComicSite.java:252)
	at jcomicdownloader.module.ParseDM5.parseComicURL(ParseDM5.java:859)
	at jcomicdownloader.module.RunModule.runSingle(RunModule.java:173)
	at jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:70)
	at jcomicdownloader.module.Run.runSingleParseModule(Run.java:169)
	at jcomicdownloader.module.Run.run(Run.java:153)
	at jcomicdownloader.ComicDownGUI$7.run(ComicDownGUI.java:2502)
	at java.lang.Thread.run(Unknown Source)

**Comment by dxzy** [comment]
sorry沒有及早回應 大大已經自行找到了 我也看不太懂這網站w
關於v5.30.170914版本
我試著去抓過去錯誤的哥布林殺手─成功
而絕望先生第10卷測試也是不行

**Comment by Kennyl** [comment]
可能 絕 字亂碼

2017-09-18 2:17 GMT+08:00 dxzy <notifications@github.com>:
