### ISSUE TITLE
v5.20.150724 無法解析tuku.CC漫画图库

### ISSUE THREAD

**Issue by hkykl** [abc9070410/JComicDownloader#24]
我下載了JComicDownloader v5.20.150724,但當想加入CC漫画图库漫畫至「下載任務」時，會出「解析失敗，無法讀入集數資訊 !!」的錯誤信息。

程式記錄如下︰
```
寫出 H:\JComicDownloader\recordList.dat 檔案
開始解析單一位址：
 ______________________________
|                            
| Run the Tuku module:     
|_______________________________

目前解析位址：http://www.tuku.cc/comic/11977/
全集頁面（main page）
(0 k) http://www.tuku.cc/comic/11977/ downloads successful!
Exception in thread "Thread-6" java.lang.StringIndexOutOfBoundsException: String index out of range: -122
	at java.lang.String.substring(Unknown Source)
	at jcomicdownloader.module.ParseTUKU.getTitleOnMainPage(ParseTUKU.java:173)
	at jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:89)
	at jcomicdownloader.module.Run.runSingleParseModule(Run.java:565)
	at jcomicdownloader.module.Run.run(Run.java:350)
選擇集數前解析得到的title：null
urlString = http://www.tuku.cc/comic/10780/
開始解析單一位址：
 ______________________________
|                            
| Run the Tuku module:     
|_______________________________

目前解析位址：http://www.tuku.cc/comic/10780/
全集頁面（main page）
寫出 H:\JComicDownloader\recordList.dat 檔案
(0 k) http://www.tuku.cc/comic/10780/ downloads successful!
Exception in thread "Thread-10" java.lang.StringIndexOutOfBoundsException: String index out of range: -122
	at java.lang.String.substring(Unknown Source)
	at jcomicdownloader.module.ParseTUKU.getTitleOnMainPage(ParseTUKU.java:173)
	at jcomicdownloader.module.RunModule.runMainProcess(RunModule.java:89)
	at jcomicdownloader.module.Run.runSingleParseModule(Run.java:565)
	at jcomicdownloader.module.Run.run(Run.java:350)
選擇集數前解析得到的title：null
```

**Comment by hkgsherlock** [comment]
又一個要改用 jsoup 的 module…

**Comment by Kennyl** [comment]
可能改在 Base Class 吧，我test了很多getxxxxTitle 都fail

**Comment by Kennyl** [comment]
只是fix 了get title on main
